apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservation-service
  namespace: next-me
  labels:
    app: reservation-service
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: reservation-service
  template:
    metadata:
      labels:
        app: reservation-service
    spec:
      imagePullSecrets:
        - name: ghcr-cred
      containers:
        - name: reservation-service
          image: ghcr.io/sparta-next-me/reservation-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 11114

          envFrom:
            - secretRef:
                name: payment-env # 요청하신 대로 payment-env 사용

          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            # Config Server 직접 주소 지정 (에러 방지 핵심)
            - name: SPRING_CONFIG_IMPORT
              value: "optional:configserver:http://config-server.next-me.svc.cluster.local:3100"
            - name: SPRING_CLOUD_CONFIG_DISCOVERY_ENABLED
              value: "false"
            - name: JAVA_OPTS
              value: "-Xms512m -Xmx768m"

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 11114
            initialDelaySeconds: 100
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 11114
            initialDelaySeconds: 150
            periodSeconds: 20

          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: reservation-service
  namespace: next-me
spec:
  selector:
    app: reservation-service
  ports:
    - name: http
      port: 11114
      targetPort: 11114
  type: ClusterIP